apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-course-registration-deployment
  labels:
    app: student-course-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-course-registration
  template:
    metadata:
      labels:
        app: student-course-registration
    spec:
      containers:
        - name: student-course-registration
          image: gaga730/student-course-registration:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "2005"
            - name: DB_NAME
              value: "student_db"