apiVersion: v1
kind: Service
metadata:
  name: student-course-registration-service
  labels:
    app: student-course-registration
spec:
  type: LoadBalancer
  selector:
    app: student-course-registration
  ports:
    - protocol: TCP
      port: 80           # Public-facing port
      targetPort: 5000   # Internal container port